CREATE TABLE IF NOT EXISTS meta_ad_accounts (
  id                  INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  platform_account_id VARCHAR(64) NOT NULL,
  name                VARCHAR(255) NOT NULL,
  currency            VARCHAR(8) NULL,
  timezone_name       VARCHAR(64) NULL,
  account_status      TINYINT UNSIGNED NULL,
  business_id         VARCHAR(64) NULL,
  business_name       VARCHAR(255) NULL,
  access_token        TEXT NOT NULL,
  connected_by        INT UNSIGNED NOT NULL,
  team_id             INT UNSIGNED NULL,
  client_id           INT UNSIGNED NULL,
  is_active           TINYINT(1) NOT NULL DEFAULT 1,
  last_synced_at      DATETIME NULL,
  created_at          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (connected_by) REFERENCES users(id),
  FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE SET NULL,
  FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE SET NULL,
  UNIQUE KEY uq_meta_ad_account (platform_account_id),
  INDEX idx_meta_ad_accounts_client (client_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
