CREATE TABLE IF NOT EXISTS google_ad_insights (
  id                INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  ad_account_id     INT UNSIGNED NOT NULL,
  campaign_id       INT UNSIGNED NULL,
  level             ENUM('account','campaign') NOT NULL,
  date_start        DATE NOT NULL,
  spend             DECIMAL(14,2) NULL DEFAULT 0,
  impressions       BIGINT NULL DEFAULT 0,
  clicks            BIGINT NULL DEFAULT 0,
  ctr               DECIMAL(8,4) NULL,
  average_cpc       DECIMAL(12,4) NULL,
  average_cpm       DECIMAL(12,4) NULL,
  conversions       DECIMAL(12,2) NULL DEFAULT 0,
  conversion_value  DECIMAL(14,2) NULL DEFAULT 0,
  roas              DECIMAL(10,4) NULL,
  fetched_at        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (ad_account_id) REFERENCES google_ad_accounts(id) ON DELETE CASCADE,
  FOREIGN KEY (campaign_id)   REFERENCES google_campaigns(id) ON DELETE CASCADE,
  UNIQUE KEY uq_google_insight (ad_account_id, campaign_id, level, date_start),
  INDEX idx_google_insights_account_date (ad_account_id, date_start)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
